# Generated by Django 3.1.2 on 2020-10-26 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_auto_20201026_1905'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Телефон', 'Телефон'), ('Компьютер', 'Компьютер'), ('Видеокарта', 'Видеокарта'), ('Жесткий диск', 'Жесткий диск')], max_length=50, null=True),
        ),
    ]
